//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SCIStorage.rc
//
#define IDD_MLP_DIALOG                  102
#define IDI_ICON_W_LEAVE                204
#define IDI_ICON_W_CHECK                222
#define IDI_ICON_W_UNCHECK              223
#define IDI_ICON_W_DETECT               226
#define IDI_ICON_W_SAVE                 227
#define IDI_ICON_W_SELECT               228
#define IDI_ICON_B_DATABASE             229
#define IDI_ICON_B_FLAG1                230
#define IDI_ICON_B_FLAG2                231
#define IDI_ICON_B_FOLDER               232
#define IDD_DLAGFINDEDAGE               258
#define IDC_TREE_MAP                    1001
#define IDC_STATIC_MAP                  1002
#define IDC_STATIC_TITLE                1003
#define IDC_COM_LABELTYPE               1003
#define IDC_STATIC_SMALLPICTURE         1004
#define IDC_STATIC_DEFECTINFO           1005
#define IDC_SCROLLBAR_MAP               1006
#define IDC_STATIC_MAPINFO              1007
#define IDC_BTN_LABEL                   1007
#define IDC_BTN_DETECT_FRONT            1008
#define IDC_BTN_DETECT                  1008
#define IDC_BTN_ADDTRAINDATA            1008
#define IDC_BTN_CANCEL                  1009
#define IDC_BTN_TRAIN                   1009
#define IDC_BTN_OPENFILE                1010
#define IDC_BTN_VERIFY                  1010
#define IDC_BTN_DETECT_BEHIND           1011
#define IDC_BTN_SAVEALL                 1011
#define IDC_BTN_SAVEFILE                1012
#define IDC_EDT_DYNTHRESH               1012
#define IDC_STC_GRAYINFO                1013
#define IDC_EDT_LEFTCOLUMN              1014
#define IDC_EDT_RIGHTCOLUMN             1015
#define IDC_STC_IMAGE                   1045
#define IDC_CHECK_WRITE_TIME            1049
#define IDC_CHECK_DISK_IMAGE            1050
#define IDC_CHECK_DISK_PROCESSINFO      1050
#define IDC_LST_ERRORLIST               1050
#define IDC_CHECK_DISK_ERRORREGION      1051
#define IDC_CHECK_DISK_SIZE             1052
#define IDC_CHECK_DISK_DELETEOK         1053
#define IDC_BTN_OPENIMAGE               1062
#define IDC_EDT_SCALEFACTOR             1066
#define IDC_EDT_LTHRESH                 1070
#define IDC_EDT_MINLIGHTTAPEAREA        1072
#define IDC_EDT_TAPEFACTOR              1076
#define IDC_COM_ERRORNAME               1080
#define IDC_EDT_JD_DARKTHRESH           1084
#define IDC_EDT_JD_MINDARKAREA          1085
#define IDC_EDT_JD_LIGHTTHRESH          1086
#define IDC_CHK_ONEKEYCLOSE             1087
#define IDC_EDT_FIRSTCOATLOWTHRESH      1089
#define IDC_STC_TITLE                   1152
#define IDC_BTN_ONEKEY                  1154
#define IDC_EDT_SECONDCOATLOWTHRESH     1158
#define IDC_STC_GRAYVALUE               1159
#define IDC_STC_FIRST                   1191
#define IDC_STC_SECOND                  1192
#define IDC_BTN_DRAWFIRSTMODEL          1193
#define IDC_BTN_DRAWSECONDMODEL         1194
#define IDC_BTN_SETGRRPARAM             1242
#define IDC_EDT_GRRSAMPLENUM            1243
#define IDC_EDT_SECONDCOATHIGHTHRESH    1248
#define IDC_EDT_FIRSTCOATHIGHTHRESH     1249
#define IDC_EDT_SECONDFOILLOWTHRESH     1250
#define IDC_EDT_SECONDFOILHIGHTHRESH    1251
#define IDC_EDT_FIRSTFOILHIGHTHRESH     1252
#define IDC_EDT_FIRSTFOILLOWTHRESH      1253
#define IDD_DIALOG_SETPARAM             3019
#define IDC_EDT_LEAKFOILTHRESH          3029
#define IDC_EDT_LEAKFOILMINAREA         3030
#define IDC_EDT_LEAKFOILDYNTHRESH       3074
#define IDC_CHK_USELEAKFOILDETECT       3076
#define IDC_CHK_USECLASSIFY             3077
#define IDC_EDT_LEAKFOILMINDEVIATION    3078
#define IDC_EDT_BUBBLEDYNTHRESH         3080
#define IDC_EDT_BUBBLEMINDIAM           3081
#define IDC_EDT_BUBBLEMINCIRCULARITY    3082
#define IDC_CHK_USEBUBBLEDETECT         3084
#define IDC_EDT_DARKLINEDYNTHRESH       3090
#define IDC_EDT_BORDEREROSIONLENGTH     3092
#define IDC_EDT_MIDDARKCOFF             3093
#define IDC_EDT_BORDERDARKCOFF          3094
#define IDC_EDT_MIDLIGHTCOFF            3095
#define IDC_EDT_BORDERLIGHTCOFF         3096
#define IDC_EDT_DARKLINEMINWIDTH        3097
#define IDC_EDT_DARKLINEMINWHRATIO      3099
#define IDC_CHK_USEDARKLINEDETECT       3100
#define IDC_EDT_LIGHTDOTMINTHRESH       3101
#define IDC_EDT_LIGHTDOTMINAREA         3104
#define IDC_CHK_USELIGHTDOTDETECT       3105
#define IDC_EDT_DARKDOTMAXTHRESH        3106
#define IDC_EDT_DARKDOTMINAREA          3109
#define IDC_CHK_USEDARKDOTDETECT        3110
#define IDC_EDT_MLPSONGJINDU            3114
#define IDC_CHK_USEFOILDETECT           3117
#define IDC_EDT_FOILDARKTHRESH          3118
#define IDC_EDT_FOILDARKMINAREA         3121
#define IDC_EDT_FOILDARKMINNUM          3122
#define IDC_MFCMENUBTN_FEATURE          3126
#define IDC_LST_TEMPFEATURE             3127
#define IDC_MFCPROPERTYGRID_ALGRITHM    3129
#define IDC_BTN_DELETE                  3130
#define IDC_BTN_ADDALGRITHM             3131
#define IDC_BTN_DELETEALGRITHM          3132
#define IDC_BTN_LOADPARAM               3134
#define IDC_CHK_USETAPEDETECT           3141
#define IDC_BTN_SAVE                    8005
#define IDD_DIALOG1                     9000
#define IDD_DIALOG_MAP                  9000
#define IDC_BUTTON1                     9000
#define IDR_MENU_RBUTTONMAP             9001
#define IDC_EDT_DISKVOLUM               9001
#define IDI_ICON1                       9002
#define IDC_EDT_CACHEDAYS               9002
#define IDD_DIALOG_PARAMSET             9003
#define IDC_EDT_SAVEPATH                9003
#define IDC_CHECK1                      9004
#define IDC_CHEK_DISK_SMALLIMAGE        9004
#define IDC_CHK_SAVEALLIMAGE            9005
#define IDC_COMBO1                      9006
#define IDC_COM_IMAGEFORMAT             9006
#define IDC_CHECK2                      9007
#define IDC_CHK_SAVELOCATION            9007
#define IDC_CHK_SAVEMARKIMAGE           9008
#define IDC_COM_OKNG                    9009
#define IDC_MFCEDITBROWSE1              9010
#define IDC_MFCBROWSE_IMAGESAVEPATH     9010
#define IDC_CHECK3                      9011
#define IDC_CHECK_CHOICEPATH            9011
#define IDC_CHK_ENABLEUPLOADIMAGE       9011
#define IDC_EDT_MACHINESN               9012
#define IDC_MFCEDITBROWSE2              9013
#define IDC_MFCEDITBROWSE_UPLOADIMAGEPATH 9013
#define ID_MENU_LOADMAP                 32771
#define ID_MENU_DELETEMAP               32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        9005
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         9014
#define _APS_NEXT_SYMED_VALUE           9000
#endif
#endif
